language: python

python:
  - 3.7
  - 3.8

install:
  - pip install cython pyarrow strawberry-graphql pytz pytest-cov codecov

script:
  - cythonize -X linetrace=True graphique/*.pyx
  - python setup.py build_ext -i --define CYTHON_TRACE_NOGIL
  - pytest -v --cov

after_success:
  - codecov

deploy:
  provider: pypi
  username: "__token__"
  password:
    secure: cwnyGTF1oC9vbrb6NKB2zLYWO3EcGNB5rG/Tzh6Nlk4cAAid/acr2dxYvqS4f81QFVnD4Xy40S4YgngZKcx3DPMd3J9ZsgBC0Ars/fJk3yov1ZfAFFc6hJZrPOdwgMpJd6dT8KlL1ZutKQG55e+Pfd3J/AXLagJ7GdAPvyciQlRcYHCNMYkpXfzqBIbbS7DfrkWpK/DW3itmva46s7O+7B28OR+a4Xi4iQpLf/8jzDx7TvVO0b4SlibPYgwH1OoG6n1SPuHWKDLB37Ain1oZa8w0/v7ZHA+iR38do5aWbZvNifMP1yMRotv7pOd/is/wP2+sZ9lTaH2noWcRkph8ph2vXuzHJzvpyVWQJ9HE5MQZiO9aqxSNRQsT5qbVaC5lKjyOhw7DJSbfurRq0Fmjb+UmQ/LwhGrCU75A1yffQZHaTVAP9eub4v7P6j1kEvx7Wa+PeymHrfRPWOmiz3JwgabB73dfTy8rkGYfo/gBJLUeZCvhClGf34dWRxDnjGIrqZIbgNEi/e8PgRGRxl+niB2/dRPNcF0XniHhvLwBNuD++VdOqXdH2woiMxFx1GLpQvlZE0YRzKTzebRQr7H/wsBuPhpGQTInrBoPhM+c+YK8Q5V1+vcMut6Dg4g5qBy6eV64qPK6skwQoJmBLB4vC8eYYOu1OpGse5W2851oZDg=
  on:
    tags: true
  distributions: "sdist"
  skip_existing: true
