language: python

python:
  - 3.7
  - 3.8

install:
  - pip install -U numpy 'graphql-core<3.1'
  - pip install pyarrow strawberry-graphql pytest-cov codecov

script:
  - pytest -v --cov

after_success:
  - codecov
