site_name: graphique
site_url: https://coady.github.io/graphique/
site_description: GraphQL service for python dataframes and parquet datasets.
theme: material

repo_name: coady/graphique
repo_url: https://github.com/coady/graphique
edit_uri: ""

nav:
  - Introduction: index.md
  - GraphQL API: api.md
  - Example Schema: schema.md
  - Example Queries: examples.ipynb
  - Core Reference: reference.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
  - mkdocs-jupyter:
      execute: true
      allow_errors: false
