name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v3
      with:
        python-version: 3.x
    - run: pip install build wheel -r docs/requirements.in
    # avoid .tar.gz name conflicts with previous project until v1.0
    - run: python setup.py sdist --formats zip
    - run: python -m build -nw
    - run: npm install
    - run: make html
    - run: python -m mkdocs gh-deploy --force
    - uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_TOKEN }}
        verbose: true
